import 'package:app_links/app_links.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:go_router/go_router.dart';
import 'package:provider/provider.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'core/constants/supabase_config.dart';
import 'core/navigation/app_router.dart';
import 'core/theme/app_theme.dart';
import 'features/auth/bloc/auth_bloc.dart';
import 'features/auth/bloc/auth_event.dart';
import 'features/auth/data/auth_repository.dart';
import 'features/profile/provider/profile_provider.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Load environment variables if .env asset exists
  try {
    await dotenv.load(fileName: ".env");
  } catch (_) {
    // Falls back to String.fromEnvironment or default configuration
  }

  // Initialize Supabase SDK safely.
  //
  // authFlowType is set to:
  //   • implicit on web — email-based recovery links embed the token in the
  //     URL fragment (#access_token=...&type=recovery). Implicit flow reads
  //     this directly without needing a stored code_verifier, so clicking the
  //     link in any tab/window works reliably.
  //   • pkce on mobile — PKCE is the recommended secure flow for native apps
  //     where the code_verifier can be kept in app-local storage.
  //
  // Using PKCE on web causes "otp_expired" errors on password-recovery links
  // because the code_verifier generated by resetPasswordForEmail() is lost
  // when the recovery link reloads or opens a new page.
  if (SupabaseConfig.isConfigured) {
    try {
      await Supabase.initialize(
        url: SupabaseConfig.url,
        publishableKey: SupabaseConfig.anonKey,
        authOptions: FlutterAuthClientOptions(
          authFlowType:
              kIsWeb ? AuthFlowType.implicit : AuthFlowType.pkce,
        ),
      );
    } catch (_) {
      // Handled during auth repository operations
    }
  }

  runApp(const InternloomApp());
}

class InternloomApp extends StatefulWidget {
  const InternloomApp({super.key});

  @override
  State<InternloomApp> createState() => _InternloomAppState();
}

class _InternloomAppState extends State<InternloomApp> {
  final _appLinks = AppLinks();

  @override
  void initState() {
    super.initState();
    _handleIncomingDeepLinks();
  }

  /// Listens for incoming deep links (OAuth callbacks from browser)
  /// and passes the URL to Supabase so it can exchange the code for a session.
  void _handleIncomingDeepLinks() {
    // Handle links received while app is already running
    _appLinks.uriLinkStream.listen((uri) {
      _processDeepLink(uri);
    }, onError: (_) {
      // Silently ignore deep link errors
    });
  }

  Future<void> _processDeepLink(Uri uri) async {
    final uriStr = uri.toString();
    if (uriStr.contains('reset-password-callback') || uriStr.contains('type=recovery')) {
      if (mounted) {
        context.read<AuthBloc>().add(const PasswordRecoveryRequested());
      }
    }
    if (uriStr.startsWith('io.internloom.app://')) {
      try {
        await Supabase.instance.client.auth.getSessionFromUrl(uri);
      } catch (_) {
        // Silently ignore session parse errors if invalid token
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return RepositoryProvider(
      create: (_) => AuthRepository(),
      child: BlocProvider(
        create: (context) => AuthBloc(
          authRepository: context.read<AuthRepository>(),
        ),
        // Student Side's profile feature (features/profile/) uses
        // Provider/ChangeNotifier rather than bloc — added here as its
        // own layer rather than converting it to bloc, since
        // ChangeNotifierProvider and BlocProvider coexist fine in one
        // widget tree and there was no reason to force a rewrite of an
        // already-working, already-verified module.
        child: ChangeNotifierProvider(
          create: (_) => ProfileProvider(),
          // _RouterShell reads AuthBloc and ProfileProvider once, stores
          // the GoRouter in StatefulWidget state so it is NEVER recreated
          // on subsequent builds — a new GoRouter would reset the entire
          // navigation stack back to initialLocation on every rebuild.
          child: _RouterShell(title: 'Internloom Student Portal'),
        ),
      ),
    );
  }
}

/// Stores the [GoRouter] in [State] so it is created exactly once,
/// regardless of how many times the parent tree rebuilds (e.g. when
/// [ProfileProvider] notifies or [AuthBloc] emits new states).
///
/// [AuthBloc] and [ProfileProvider] references are captured in
/// [initState] — before [build] runs for the first time — and passed
/// directly into [AppRouter.buildRouter]. This avoids the
/// [BuildContext] inside GoRouter's redirect callback, which would
/// otherwise fail to resolve providers via [context.read] because the
/// redirect runs on the router's own internal navigator context.
class _RouterShell extends StatefulWidget {
  const _RouterShell({required this.title});
  final String title;

  @override
  State<_RouterShell> createState() => _RouterShellState();
}

class _RouterShellState extends State<_RouterShell> {
  late final GoRouter _router;

  @override
  void initState() {
    super.initState();
    // context.read is safe here because initState runs after the first
    // build frame — the BlocProvider and ChangeNotifierProvider are
    // already in the tree at this point.
    _router = AppRouter.buildRouter(
      authBloc: context.read<AuthBloc>(),
      profileProvider: context.read<ProfileProvider>(),
    );
  }

  @override
  void dispose() {
    _router.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: widget.title,
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme,
      routerConfig: _router,
    );
  }
}
