import 'package:app_links/app_links.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:provider/provider.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'core/constants/supabase_config.dart';
import 'core/theme/app_theme.dart';
import 'features/auth/bloc/authentication_bloc.dart';
import 'features/auth/bloc/authentication_event.dart';
import 'features/auth/data/authentication_repository.dart';
import 'features/auth/presentation/screens/splash_screen.dart';
import 'features/profile/provider/profile_provider.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Load environment variables if .env asset exists
  try {
    await dotenv.load(fileName: ".env");
  } catch (_) {
    // Falls back to String.fromEnvironment or default configuration
  }

  // Initialize Supabase SDK safely.
  //
  // authFlowType is set to:
  //   • implicit on web — email-based recovery links embed the token in the
  //     URL fragment (#access_token=...&type=recovery). Implicit flow reads
  //     this directly without needing a stored code_verifier, so clicking the
  //     link in any tab/window works reliably.
  //   • pkce on mobile — PKCE is the recommended secure flow for native apps
  //     where the code_verifier can be kept in app-local storage.
  //
  // Using PKCE on web causes "otp_expired" errors on password-recovery links
  // because the code_verifier generated by resetPasswordForEmail() is lost
  // when the recovery link reloads or opens a new page.
  if (SupabaseConfig.isConfigured) {
    try {
      await Supabase.initialize(
        url: SupabaseConfig.url,
        publishableKey: SupabaseConfig.anonKey,
        authOptions: FlutterAuthClientOptions(
          authFlowType:
              kIsWeb ? AuthFlowType.implicit : AuthFlowType.pkce,
        ),
      );
    } catch (_) {
      // Handled during auth repository operations
    }
  }

  runApp(const InternloomApp());
}

class InternloomApp extends StatefulWidget {
  const InternloomApp({super.key});

  @override
  State<InternloomApp> createState() => _InternloomAppState();
}

class _InternloomAppState extends State<InternloomApp> {
  final _appLinks = AppLinks();

  @override
  void initState() {
    super.initState();
    _handleIncomingDeepLinks();
  }

  /// Listens for incoming deep links (OAuth callbacks from browser)
  /// and passes the URL to Supabase so it can exchange the code for a session.
  void _handleIncomingDeepLinks() {
    // Handle links received while app is already running
    _appLinks.uriLinkStream.listen((uri) {
      _processDeepLink(uri);
    }, onError: (_) {
      // Silently ignore deep link errors
    });
  }

  Future<void> _processDeepLink(Uri uri) async {
    final uriStr = uri.toString();
    if (uriStr.contains('reset-password-callback') || uriStr.contains('type=recovery')) {
      if (mounted) {
        context.read<AuthenticationBloc>().add(const PasswordRecoveryModeTriggered());
      }
    }
    if (uriStr.startsWith('io.internloom.app://')) {
      try {
        await Supabase.instance.client.auth.getSessionFromUrl(uri);
      } catch (_) {
        // Silently ignore session parse errors if invalid token
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return RepositoryProvider(
      create: (_) => AuthenticationRepository(),
      child: BlocProvider(
        create: (context) => AuthenticationBloc(
          authenticationRepository: context.read<AuthenticationRepository>(),
        ),
        // Student Side's profile feature (features/profile/) uses
        // Provider/ChangeNotifier rather than bloc — added here as its
        // own layer rather than converting it to bloc, since
        // ChangeNotifierProvider and BlocProvider coexist fine in one
        // widget tree and there was no reason to force a rewrite of an
        // already-working, already-verified module.
        child: ChangeNotifierProvider(
          create: (_) => ProfileProvider(),
          child: MaterialApp(
            title: 'Internloom Student Portal',
            debugShowCheckedModeBanner: false,
            theme: AppTheme.lightTheme,
            home: const SplashScreen(),
          ),
        ),
      ),
    );
  }
}
